[package]
name = "actix-qrcode"
version = "0.2.3"
edition = "2021"

[dependencies]
base64 = "0.22.1"
actix-web = "4.11.0"
fast_qr = { version = "0.13.1", features = ["image"] }
serde = { version = "1.0.219", features = ["derive"] }
