[package]
name = "actix-qrcode"
version = "0.1.1"
edition = "2021"

[dependencies]
actix-web = "4.2.1"
fast_qr = { version = "0.8.1", features = ["image"] }
serde = { version = "1.0.149", features = ["derive"] }
