[package]
name = "actix-qrcode"
version = "0.2.0"
edition = "2021"

[dependencies]
actix-web = "4.3.1"
fast_qr = { version = "0.8.6", features = ["image"] }
serde = { version = "1.0.163", features = ["derive"] }
